language: go

sudo: false

go:
  - 1.8

services:
    - mysql

before_install:
      - go get -t -v ./...
      - mysql -e 'CREATE DATABASE IF NOT EXISTS claimr;'

script:
      - make test

after_success:
      - bash <(curl -s https://codecov.io/bash)
