language: go

sudo: false

go:
  - 1.8

services:
  - mysql

before_install:
  - go get -t -v ./...
  - mysql -e 'CREATE DATABASE IF NOT EXISTS claimr;'

env:
  global:
    - CLAIMR_DATABASE=root@/claimr?charset=utf8&parseTime=True&loc=Local
script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
